cparse/cparse

Makefile
README.md
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

Now it is possible to compile an expression to RPN once,
and then evaluate it several times with different sets of variables.
This is possible using the new class constructor and/or the compile() function.
This is useful if you want to evaluate an expression several times in different contexts, e.g.:
```c++
std::map<std::string, double> vars;
vars["pi"] = 3.14;
calculator c1("pi-b");
vars["b"] = 0.14;
std::cout << c1.eval(&vars) << std::endl; // 3
vars["b"] = 2.14;
std::cout << c1.eval(&vars) << std::endl; // 1
```
None of the old functionality has changed. Everything still works as expected.
I have also added some unrelated stuff:
- A new str() function, it is helpful to debug.
- Added a new case to Makefile so you can call "make run", which builds and executes the tests.
- Some new …

Add a compile() feature to class instance

---

shunting-yard.cpp
shunting-yard.h

I changed the TokenBase and Token a little bit so we can keep track of the type of the Token. This way we can use static_cast instead dynamic_cast, which should be more efficient.

Replace dynamic_cast for static_cast for speed

---

Makefile
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

Hello @bamos, this is a major change, now the framework is ready to support new variable types as:
- `string`
- `boolean`
- `objects`
This is now possible because the evaluation now works with `TokenBase*` all the time instead
of using doubles, and the operations now check for operand types before being applied.
I think this code is very good, its clean and easy to understand (I tried to implement it 3 times with different strategies, this one is the only one that looked nice).
Some drawbacks that I plan to fix:
The variable map now is a TokenBase* map. This means that we cannot do:
```c++
vars["b1"] = 3.14;
// nor
std::cout << calculator::calculate("1+2") << std::endl;
```
But instead we need to write:
```c++
map["b1"] = new Token<double>(3.14, NUM);
// or
std::cout << …
```

Add multi-type support 

---

Makefile
packToken.cpp
packToken.h
shunting-yard-exceptions.h
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

Now the old way of accessing variables with the `TokenMap_t` works again, e.g.:
```c++
TokenMap_t map;
map["pi"] = 3.14;
std::cout << map["pi"] << std::endl; // 3.14
```
drawbacks:
The `packToken` code is not very simple, but is short enough to be understood.
everytime a new type is added we will need to update `packToken::str()` function and add an explicit coersion function `packToken::as<NewType>()` and an implicit constructor for this new type as well.
The bright side is that I think we won't use many more types, other than: String, Boolean and Map(Dict) and maybe a List type in the future.
Next work: Add string type, string operations and string literal recognition.

Add packToken as a facade for TokenBase*

---

packToken.cpp
packToken.h
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

Hello @bamos, now this is an interesting commit (the aim of all this new commits), now we support MAP operators like in interpreted languages, e.g.:
```c++
tmap = new TokenMap_t;
vars["map"] = tmap;
tmap["foo"] = 3;
calculator::calculate("map['foo'] == 3", true, &vars);
```

Add MAP type and subscript operator: `[]`

---

packToken.cpp
packToken.h
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

Hello @bamos, I've added a `class Scope` that contain a list of `TokenMap_t*` so that the first one would be the global scope, and the rest the local scopes. Its use is optional and the API is the same as before.
The trick is this constructor: `Scope::Scope(TokenMap_t* tmap)` that allows for implicit conversion from TokenMap_t* to Scope, so we can keep the old function calls working as they did before, but now the API expects a `Scope` class where it used to expect a `TokenMap_t*`.
I also found a bug when you do:
```
calculator c1, c2("1+1");
c1 = c2; // seg fault
calculator c3(c2); // seg fault
```
And I fixed that on the last commit.
Also, i noticed a memory leak problem, it is older than these commits, I will investigate it.

Add Scope concept, and fix some bugs

---

packToken.cpp
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

Finally we can close the issue #3.
This merge adds support for assignment of variables:
```c++
a = 10
a = b
a = c.d
```
Make the evaluation of the operator `=` to be from right-to-left so this works:
```c++
a = b = c = 10
```
And also allow assignment on Tokens of type MAP:
```c++
a.b = c['foo'] = d + 4
```
I did not figure out how to make Travis check it for me yet. But as soon as it does I'll fix it =].
Edit: just fixed it =].

Add support for the assignment operator

---

functions.cpp
functions.h
objects.cpp
objects.h
pack.h
packToken.cpp
packToken.h
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

This PR is a major Refactor.
To make the garbage collector work, we created the `pack<>` template, that is responsible for keeping a reference to a map and/or a list avoiding to copy it often.
But this causes a problem: Now we have 2 pairs of classes that are basically the same thing:
`TokenMap` and `packMap` (i.e. `pack<TokenMap*>`)
`TokenList` and `packList` (i.e. `pack<TokenList*>`)
This redundancy might be confusing for our users and probably will make de code harder to maintain.
Other problem is that it is not possible to have a Token that is both: A `Map` and an `Iterable` because it would require us to make packMap Iterable, but it is a template built for other purpose.
With all that in mind we removed the `packMap` and `packList` typedefs, and made `TokenMap` and `TokenList` …

Simplify containers

---

functions.cpp
objects.cpp
objects.h
packToken.cpp
packToken.h
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

This PR, contains some bug fixing, some refactoring and among them the most important are:
- Add a TokenMap::findMap() function, works like find() but return the original map. Can be useful when managing references to variables, to make sure it will point to the original variable, on the original map. (pointing the reference directly to the variable would not be safe since the garbage collector only guarantee access to map and list references).
- Protect global scope from assignments; Now if the user wants to change the global scope it will need to have a reference to it, i.e. a `global` built-in variable referencing the global scope.
- Add the integer (INT) type. It does not add operations to work with it, but all operations that work with doubles were adapted to accept integers as well. …

Minor updates

---

Makefile
functions.cpp
functions.h
objects.cpp
objects.h
packToken.cpp
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

The major changes are these 3:
- Tuples now inherit from TokenList and are managed by the same garbage collector.
- Map now have the built-in functions: pop() and len()
- The map constructor now accepts Special Tuples, e.g.:
```javascript
my_map = map('val1': 10, 'val2': 20, 'val3': 30)
print(my_map) // { "val1": 10, "val2": 20, "val3": 30 }
```
Please note that these tuples will work as key-value arguments for any function. A lot like it does in Python with the operator `=`. So if you want to access the last argument of a function with many arguments you just need to write: `func('arg_name': 'arg_value')`.
Also if the key-value pair does not refer to an existing function argument it will be added to a built-in dictionary called: `kwargs` available inside the functions scope (much like …

Improve support to Map and Tuple

---

Makefile
README.md
functions.cpp
functions.h
objects.cpp
operations.cpp
packToken.cpp
shunting-yard-exceptions.h
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

Hey Brandon,
this is probably the last big PR I'll submit.
Now the operations, and operation precedence order are defined outside the calculator class.
This allows for users to define their own operations without need for messing with the shunting-yard code.
This PR adds 3 new features:
1. Now it's available the `make release` command. It generates 2 optimized `.o` files that includes all our library: `core-shunting-yard.o` and `operations.o`
2. If an user want to declare his own operations he just needs to:
A. Copy file `operations.cpp` into his project (or make a new empty `.cpp` file)
B. Link `core-shunting-yard.o` only to his code and not `operations.o`
C. Edit his `operations.cpp` file any way he wants (using the original as model) and compile it.
The problem with this method is that …

Decouple operations

---

operations.cpp
shunting-yard.cpp
shunting-yard.h

Now the user has access to the `calculator::default_rWordMap()` map.
this map links reserved words, i.e. std::strings with functions
specialized in parsing them. These function can be defined
by the user.
Now it is possible for example to declare a function inside an expression.
Currently it is only used for 3 reserved words:
- True
- False
- None
This is a good thing since it solves issue #32 of having
these reserved word values hard-coded.

Expose an API to define the parsing of reserved words

---

shunting-yard.cpp
shunting-yard.h

This is a small fix.
The last merge exposed an API to describe the effects a reserved word should cause on the parsing process. But this API was not exposing the local scope, and that is an important variable to have.
This commit fix it.

Make scope available on the rpnBuilder class

---

builtin-operations.cpp
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

Now you can define how you want an operator
to be parsed just like you do with a reserved word:
```C++
void LineComment(const char* expr, const char** rest, rpnBuilder* data) {
while (*expr && *expr != '\n') ++expr;
if (*expr != '\0') ++expr;
*rest = expr;
}
class Startup {
Startup() {
rWordMap_t& rwMap = calculator::default_rWordMap();
rwMap["#"] = &LineComment;
rwMap["//"] = &LineComment;
}
};
```
This commit also changes the return type of these reserved word
parser functions. Before they would return a TokenBase* type,
now they return void.
The reasoning is that if you want to add a new token, you already
have access to the `data->rpn` queue, so why add 2 different ways
to do the same thing? Also when parsing a comment for example
there is no sense in returning any value.
So now if …

Expose parsing of operators to API

---

builtin-features.cpp
objects.h
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

Now if you want to define your operator to associate from right to left, instead of the default, i.e. from left to right you just need to define its priority as a negative number. The actual priority value used will be the mod of it, but when evaluating it will associate on the reverse order.
To allow that it was necessary to change a little the API:
```C++
OppMap_t& opp = calculator::default_opPrecedence();
// Before:
opp["my_op"] = my_op_priority;
// Now:
opp.add("my_op", -my_op_priority);
```
Minor bug fix: The TokenList operator[] now throws out_of_range exceptions instead of causing memory access errors. (to avoid this error check for speed just use the TokenList::list()::operator[] API)
Minor bug fix: The call operator `()` used to take over any operation with a Function on the left …

Op Associativity API + Minor fixes, refactors and updates

---

builtin-features.cpp
functions.cpp
objects.cpp
objects.h
packToken.cpp
packToken.h
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

1. Add the concept of `reserved character` 08aecfd, changing the way to add reserved words, and allowing for reserving the meaning of single characters regardless if they are followed by other characters that look like operators, e.g.: `/my reg exp/ or /!my reg exp/`, in both cases the character `/` should trigger the evaluation of a regular expression, and that was not possible before where `/!` would be missinterpreted as an operator. Now to the syntax for adding a reserved word or character is this:
```C++
parserMap_t& parser = calculator::Default().parserMap;
parser.add("new", &new_behavior);
parser.add('/', &regex_delimiter);
```
2. Make an important refactor on 44bdcec that groups together `OppMap_t`, `rWordMap_t` and `opMap_t` into a class named `Config_t`. To access these values …

Add some small improvements

---

Makefile

This was changed because this options is not recognized on macOS
and possibly Windows too.

Make ld -O1 option conditional to Linux builds

---

Makefile
builtin-features/operations.inc
builtin-features/typeSpecificFunctions.inc
catch.cpp
containers.h
packToken.cpp
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

At high warning levels, MSVC complains about signed/unsigned comparisons, and conversions from 64 to 32 bit integers. Using the size_t and ptrdiff_t datatypes makes those warnings go away.
Also adding a few explicit casts for conversions between float and integer values where flagged as dangerous by the compiler.

Fix MSVC warnings

---

catch.cpp
shunting-yard.cpp
shunting-yard.h
test-shunting-yard.cpp

See included test.
Compiling an expression containing a stray plus symbol used to throw an error message that said "Expected operand after unary operator `L+`". Calling normalize_op when building this message results in the much friendlier "Expected operand after unary operator `+`" (without the L).

Normalize unary operator in error message

---

README.md
functions.h

1. fix missing namespace inREADME.md examples, so users can copy and paste and run example code.
2. add a space after include keyword in functions.h by the way.

fix missing namespace in README.md examples

---

builtin-features/functions.inc
builtin-features/operations.inc

map operator [] will insert value if not find, which may cause segmentation fault in the case of multi-threading.

fix segment fault when multi-threading
